### ISSUE TITLE
Crash at startup since version 1.3.0

### ISSUE THREAD

**Issue by francois-ferrandis** [alberthier/git-webui#22]
No matter the port, I always get:
```
Traceback (most recent call last):
  File "/home/francois/.git-webui/release/libexec/git-core/git-webui", line 317, in <module>
    httpd = HTTPServerIPng((host, port), WebUiRequestHandler)
  File "/home/francois/.git-webui/release/libexec/git-core/git-webui", line 55, in __init__
    0, 0, socket.IPPROTO_TCP)[0]
gaierror: [Errno -2] Name or service not known
```

**Comment by targuan** [comment]
Can you try to start with --host 0.0.0.0 ?

**Comment by francois-ferrandis** [comment]
It works!

**Comment by alberthier** [comment]
v1.4.0 fixes the issue.
just update your clone of git-webui
