### ISSUE TITLE
auto_update: invalid argument

### ISSUE THREAD

**Issue by sigod** [alberthier/git-webui#28]
```
$ git webui
Traceback (most recent call last):
  File "C:/Users/sigod/.git-webui/release/libexec/git-core/git-webui", line 280, in <module>
    auto_update()
  File "C:/Users/sigod/.git-webui/release/libexec/git-core/git-webui", line 227, in auto_update
    delta = datetime.datetime.now() - datetime.datetime.fromtimestamp(fetch_head_mtime)
OSError: [Errno 22] Invalid argument
```

Tried on a number of projects. With `autoupdate` set to both `true` and `false`. Also, tried removing `autoupdate` to no avail.

Windows 7, x64
git version 2.8.1.windows.1
Python 3.6.0

**Comment by alberthier** [comment]
fromtimestamp(0) fails with python 3.6

I just fixed the issue.
you just have to cd in your `git-webui` repo and `git pull` to fetch the update
